#project_id: 674810
#api_token: db861a847d7108a14571283d909426036ffbab2480658ab6ae05ed519b8a7ffd0741f0a3337ce680

preserve_hierarchy: true

files:
  - source: src/i18n/locales/default/**/*.json
    translation: '/src/i18n/locales/%locale%/%original_file_name%'
